spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:SGw_D6o74Licyq_I9B6_DbyGXoa9L0dOQjRBFt4n1wP3ejZJ@a40f5968-5336-4958-bf4b-e12cab8742fa.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0